version: '3.9'

services:

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: kanjidb
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
